# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Kubeflow Container Registry'
    repository: 'kubeflowregistry.azurecr.io/kubeflow/preprocess'
    command: 'buildAndPush'
    Dockerfile: 'code/preprocess/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Kubeflow Container Registry'
    repository: 'kubeflowregistry.azurecr.io/kubeflow/train'
    command: 'buildAndPush'
    Dockerfile: 'code/training/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Kubeflow Container Registry'
    repository: 'kubeflowregistry.azurecr.io/kubeflow/score'
    command: 'buildAndPush'
    Dockerfile: 'code/scoring/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Kubeflow Container Registry'
    repository: 'kubeflowregistry.azurecr.io/kubeflow/release'
    command: 'buildAndPush'
    Dockerfile: 'code/release/Dockerfile'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
